from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
import json
from typing import TypeAlias

from projectkoios.ingestors.backends import BackendAdapter
from projectkoios.ingestors.retrieval import RetrievalResult


JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]
JsonObject: TypeAlias = dict[str, JsonValue]


class AnswerFormat(StrEnum):
    """Supported answer output formats."""

    CITED_SUMMARY = "cited_summary"
    STRUCTURED_JSON = "structured_json"


@dataclass(frozen=True, slots=True)
class Answer:
    """Composed GraphRAG answer.

    Args:
        query: Original query text.
        format: Output format used for the answer.
        text: Rendered answer text.
        citations: Citation labels included in the answer.
        payload: JSON-compatible answer payload.
    """

    query: str
    format: AnswerFormat
    text: str
    citations: tuple[str, ...]
    payload: JsonObject


class AnswerComposer:
    """Compose GraphRAG answers from retrieval results and optional backends."""

    def compose(
        self,
        query: str,
        retrieval: RetrievalResult,
        *,
        format: AnswerFormat,
        backend: BackendAdapter | None = None,
        backend_on_failure: str = "error",
    ) -> Answer:
        """Compose an answer for a query and retrieval result.

        Args:
            query: Original query text.
            retrieval: Retrieved evidence for the query.
            format: Desired answer format.
            backend: Optional generation backend.
            backend_on_failure: Failure behavior, either error or fallback.

        Returns:
            Composed answer object.
        """

        # Citations preserve the evidence citation order.
        citations: tuple[str, ...] = tuple(evidence.citation for evidence in retrieval.evidence)
        # Evidence lines provide the evidence block for backend prompting.
        evidence_lines: list[str] = [f"- {evidence.title} ({evidence.citation})" for evidence in retrieval.evidence]
        # Evidence block is included in the backend prompt.
        evidence_block: str = "\n".join(evidence_lines) if evidence_lines else "- no evidence found"
        # Prompt is the backend-facing answer generation request.
        prompt: str = (
            f"Question: {query}\n\n"
            f"Evidence:\n{evidence_block}\n\n"
            "Write a concise answer with citations."
        )
        # Body is generated by a backend or deterministic fallback.
        body: str = self.compose_body(
            prompt=prompt,
            query=query,
            retrieval=retrieval,
            backend=backend,
            backend_on_failure=backend_on_failure,
        )
        # Cited body appends citation bullets for human-readable output.
        cited_body: str = self.append_citations(body, citations)

        if format == AnswerFormat.STRUCTURED_JSON:
            # Payload is the JSON-compatible structured answer object.
            payload: JsonObject = {
                "query": query,
                "answer": cited_body,
                "citations": list(citations),
                "evidence": [
                    {
                        "title": evidence.title,
                        "citation": evidence.citation,
                        "excerpt": evidence.excerpt,
                        "score": evidence.score,
                    }
                    for evidence in retrieval.evidence
                ],
            }
            return Answer(query=query, format=format, text=json.dumps(payload, indent=2, ensure_ascii=False), citations=citations, payload=payload)

        # Fallback payload keeps cited-summary answers machine-readable.
        fallback_payload: JsonObject = {
            "query": query,
            "answer": cited_body,
            "citations": list(citations),
        }
        return Answer(query=query, format=format, text=cited_body, citations=citations, payload=fallback_payload)

    def compose_body(
        self,
        *,
        prompt: str,
        query: str,
        retrieval: RetrievalResult,
        backend: BackendAdapter | None,
        backend_on_failure: str,
    ) -> str:
        """Compose answer body text from backend or fallback.

        Args:
            prompt: Backend prompt text.
            query: Original query text.
            retrieval: Retrieved evidence for fallback output.
            backend: Optional generation backend.
            backend_on_failure: Failure behavior, either error or fallback.

        Returns:
            Generated or fallback answer body.
        """

        if backend is None:
            return self.fallback_summary(query, retrieval)
        try:
            return backend.generate(prompt)
        except Exception:
            if backend_on_failure != "fallback":
                raise RuntimeError(f"backend '{backend.name}' failed while composing answer") from None
            return self.fallback_summary(query, retrieval)

    def fallback_summary(self, query: str, retrieval: RetrievalResult) -> str:
        """Return a deterministic fallback answer body.

        Args:
            query: Original query text.
            retrieval: Retrieved evidence.

        Returns:
            Fallback answer body text.
        """

        if not retrieval.evidence:
            return f"No relevant evidence found for: {query}"
        # Evidence lines summarize each retrieved evidence item.
        evidence_lines: list[str] = [f"{evidence.title} — {evidence.excerpt}" for evidence in retrieval.evidence]
        # Lines compose the deterministic fallback answer body.
        lines: list[str] = [f"Answering: {query}", "", *evidence_lines]
        return "\n".join(lines)

    def append_citations(self, body: str, citations: tuple[str, ...]) -> str:
        """Append citation bullets to a body when citations exist.

        Args:
            body: Answer body text.
            citations: Citation labels to append.

        Returns:
            Body with citations appended when present.
        """

        if not citations:
            return body
        # Lines combines the body and citation bullet list.
        lines: list[str] = [body.rstrip(), "", "Citations:"]
        lines.extend(f"- {citation}" for citation in citations)
        return "\n".join(lines)
